import { EventEntity, EventPlan, AgentActionLog } from '../types.js';
import { db } from '../db.js';
import { generateAgentResponse } from '../aiService.js';

export interface EventManagerInput {
  event: EventEntity;
  venueResult: any;
  vendorResult: any;
  budgetResult: any;
  scheduleResult: any;
  commResult: any;
  isReplanning?: boolean;
  deltaSummary?: string;
}

export interface EventManagerOutput {
  plan: EventPlan;
  actionLog: AgentActionLog;
}

export async function runEventManager(input: EventManagerInput): Promise<EventManagerOutput> {
  const startTime = Date.now();
  const { event, venueResult, vendorResult, budgetResult, scheduleResult, commResult, isReplanning, deltaSummary } = input;

  const isOverBudget = budgetResult.budget.is_over_budget;

  const attendees = event.expected_attendees ?? 500;
  const budgetTotal = event.total_budget ?? 500000;

  const recommendations: string[] = [
    `Venue ${venueResult.selectedVenue.name} reserved (${venueResult.selectedVenue.capacity} max capacity).`,
    `Scaled ${vendorResult.selectedVendors.length} vendor categories for ${attendees} attendees.`,
    isOverBudget
      ? `CRITICAL BUDGET WARNING: Projected expenditure exceeds target budget by ₹${(budgetResult.budget.over_budget_amount || 0).toLocaleString('en-IN')}. Review AI proposed cost-saving options.`
      : `Budget status optimal with ₹${(budgetResult.budget.remaining_budget || 0).toLocaleString('en-IN')} contingency balance remaining.`
  ];

  if (isReplanning) {
    recommendations.unshift(`DYNAMIC REPLANNING EXECUTED: Re-calibrated plan for ${attendees} attendees.`);
  }

  // Synthesis via Gemini AI
  const systemPrompt = `You are the Event Manager Orchestrator for EventPilot AI.
Synthesize the multi-agent results into a crisp executive summary. Return JSON:
{
  "executive_summary": "3-sentence executive briefing summarizing venue selection, vendor scaling, budget status, and next steps."
}`;

  const userPrompt = `Event: ${event.name} (${event.type})
Attendees: ${attendees}
Budget: ₹${budgetTotal.toLocaleString('en-IN')}
Mode: ${isReplanning ? 'DYNAMIC REPLANNING' : 'INITIAL PLANNING'}
Delta: ${deltaSummary || 'N/A'}
Venue: ${venueResult.selectedVenue.name} (₹${(venueResult.selectedVenue.cost_per_day || 0).toLocaleString('en-IN')}/day)
Budget Total: ₹${(budgetResult.budget.estimated_total || 0).toLocaleString('en-IN')} (Over budget: ${isOverBudget})
Vendor Count: ${vendorResult.selectedVendors.length}`;

  let executiveSummary = `${event.name} master plan generated by EventPilot AI autonomous agent mesh. ` +
    `Venue ${venueResult.selectedVenue.name} and ${vendorResult.selectedVendors.length} vendor partners auto-calibrated for ${attendees} expected attendees. ` +
    (isOverBudget
      ? `Action required: Estimated cost exceeds budget target by ₹${(budgetResult.budget.over_budget_amount || 0).toLocaleString('en-IN')}.`
      : `Financial forecast balanced within ₹${budgetTotal.toLocaleString('en-IN')} total allocation.`);

  const aiResultText = await generateAgentResponse(systemPrompt, userPrompt);
  if (aiResultText) {
    try {
      const parsed = JSON.parse(aiResultText);
      if (parsed.executive_summary) executiveSummary = parsed.executive_summary;
    } catch (e) {
      // Fallback
    }
  }

  const finalPlan: EventPlan = {
    event_id: event.id,
    selected_venue: venueResult.selectedVenue,
    selected_vendors: vendorResult.selectedVendors,
    budget: budgetResult.budget,
    schedule: scheduleResult.schedule,
    generated_messages: commResult.generatedMessages,
    executive_summary: executiveSummary,
    recommendations,
    last_updated: new Date().toISOString()
  };

  const executionTime = Date.now() - startTime;
  const actionLog: AgentActionLog = {
    id: `act-${Date.now()}-mgr`,
    event_id: event.id,
    agent_name: 'Event Manager',
    action_type: isReplanning ? 'ORCHESTRATE_DYNAMIC_REPLAN' : 'ORCHESTRATE_INITIAL_PLAN',
    input_summary: `Orchestrating 5 sub-agents for ${event.name} (${event.expected_attendees} attendees)`,
    output_summary: `Master plan synthesized. Budget status: ${isOverBudget ? 'OVER BUDGET' : 'BALANCED'}`,
    status: isOverBudget ? 'Warning' : 'Success',
    execution_time_ms: executionTime,
    timestamp: new Date().toISOString(),
    details: { isReplanning, isOverBudget, estimatedTotal: budgetResult.budget.estimated_total }
  };

  db.logAgentAction(actionLog);

  return {
    plan: finalPlan,
    actionLog
  };
}
